version: '3.2'
services:
  node:
    image: node:16.20.0-alpine
    container_name: node
    restart: always
    ports:
      - 3000:3000
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - MICRO_IPCORE_DEVICE=http://micro-ipcore-device:5683
      - MICRO_IPCORE_CLOUD=http://micro-ipcore-cloud:5684
    command: npm run start
  micro-ipcore-device:
    image: docker.io/acklio/micro-ipcore
    container_name: micro-ipcore-device
    restart: always
    volumes:
      - ./demo/webhook-docker:/opt/acklio/demo/webhook
    command: 
      - webhook
      - --config=/opt/acklio/demo/webhook/config-device.json
      - --context_path=/opt/acklio/demo/webhook/context.json
  micro-ipcore-cloud:
    image: docker.io/acklio/micro-ipcore
    container_name: micro-ipcore-cloud
    restart: always
    volumes:
      - ./demo/webhook-docker:/opt/acklio/demo/webhook
    command: 
      - webhook
      - --config=/opt/acklio/demo/webhook/config-server.json
      - --context_path=/opt/acklio/demo/webhook/context.json

    